./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/small/carli1
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/small/carli2
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/small/carli3
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/small/carli4
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/small/carli5
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/small/super1
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/small/super2
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/small/super3
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/small/super4
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/small/super5
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/small/hcao1
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/small/hcao2
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/small/hcao3
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/small/hcao4
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/small/hcao5
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/small/grati1
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/small/grati2
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/small/grati3
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/small/grati4
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/small/grati5
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/small/aba1
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/small/aba2
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/small/aba3
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/small/aba4
./resources/filler_vm -f ./resources/maps/map00 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/small/aba5