
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/big/carli1
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/big/carli2
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/big/carli3
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/big/carli4
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/big/carli5
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/big/super1
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/big/super2
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/big/super3
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/big/super4
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/big/super5
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/big/hcao1
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/big/hcao2
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/big/hcao3
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/big/hcao4
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/big/hcao5
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/big/grati1
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/big/grati2
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/big/grati3
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/big/grati4
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/big/grati5
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/big/aba1
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/big/aba2
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/big/aba3
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/big/aba4
./resources/filler_vm -f ./resources/maps/map02 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/big/aba5