./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/mid/carli1
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/mid/carli2
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/mid/carli3
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/mid/carli4
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/carli.filler > ./sample_maps/mid/carli5
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/mid/super1
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/mid/super2
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/mid/super3
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/mid/super4
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/superjeannot.filler > ./sample_maps/mid/super5
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/mid/hcao1
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/mid/hcao2
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/mid/hcao3
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/mid/hcao4
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/hcao.filler > ./sample_maps/mid/hcao5
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/mid/grati1
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/mid/grati2
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/mid/grati3
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/mid/grati4
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/grati.filler > ./sample_maps/mid/grati5
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/mid/aba1
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/mid/aba2
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/mid/aba3
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/mid/aba4
./resources/filler_vm -f ./resources/maps/map01 -p1 ./srcs/filler -p2 ./resources/players/abanlin.filler > ./sample_maps/mid/aba5
